#!/bin/bash

if [[ ! $(find ~/ -maxdepth 1 -type d -name ".trash") ]]; then
	echo "Trash bin is does not exist"
	exit 1
fi

if [[ $# -ne 1 ]]; then
	echo "Must be only one parameter - filename"
	exit 1
fi

name=$1
visited="false"
while read -u 3 line
do
	fullname=$(echo $line | awk -e '$3 ~ /\/'"$name"'$/ {print $3}')
	link=$(echo $line | awk -e '$3 ~ /\/'"$name"'$/ {print $6}')
	if [[ $fullname ]]; then
		visited=true
		read -p "Untrash file $fullname? (y/n) : " ans
		if [[ $ans == "y" ]]; then
			path=${fullname%/*}
			if [[ -d $path ]]; then
				while [[ -f $path/$name ]]; do
					read -p "File alread exist. Enter new : " name
				done
				ln ~/.trash/$link $path/$name
			else
				while [[ -f ~/$name ]]; do
					read -p "File alread exist. Enter new name : " name
				done
				echo "Dir is not exist"
				ln ~/.trash/$link ~/$name
			fi
			rm ~/.trash/$link
			sed -i "\|$line|d" ~/.trash.log
		else
			if [[ $ans != "n" ]]; then
				echo "Ivalid input"
				exit 1
			fi
		fi
	fi
done 3< ~/.trash.log

if [[ $visited == "false" ]]; then
	echo "Can't find file - $name"
fi

if [[ -z "$(ls -A ~/.trash)" ]]; then
	echo 0 > ~/index
fi


